name: .NET

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish for win-x64
      run: dotnet publish -c Release -r win-x64 -p:PublishSingleFile=true --self-contained true
    - name: Publish for win-arm64
      run: dotnet publish -c Release -r win-arm64 -p:PublishSingleFile=true --self-contained true
